version: '3'

services:
  venmo-scheduler:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3005"

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - venmo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgresd

volumes:
  venmo-data:
