version: '3'

services:
  venmo-scheduler:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3005"
    volumes:
      - node_modules:/app/node_modules/
      - ./:/app/ ## anonymous volume so that the files can be watched by nodemon. TODO: figure out why this is needed

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - venmo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgresd

volumes:
  venmo-data:
  node_modules:
