name: Monthly Housing Payment

# Controls when the workflow will run
on:
  schedule:
    - cron:  '5 * * * *'
    # '45 0 1 * *'

jobs:
  make_payments:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      # Runs a single command using the runners shell
      - name: Execute run.py
        run: python3 ./action_scripts/run.py
        env:
          key: ${{ secrets.TEST_TOKEN }}
